#!/bin/bash
set -e

CFG_DIR="/etc/dimmy"

CFG_FILES=(
    "dimmyd.conf.yaml"
    "rules.conf.yaml"
    "dimmy.conf.example"
)

for CFG_FILE in "${CFG_FILES[@]}"; do
    FULL_CFG_FILE="${CFG_DIR}/${CFG_FILE}"
    EXAMPLE_FILE="${FULL_CFG_FILE}.example"
    if [ ! -f "${FULL_CFG_FILE}" ] && [ -f "${EXAMPLE_FILE}" ]; then
        cp "${EXAMPLE_FILE}" "${FULL_CFG_FILE}"
    fi
    rm "${EXAMPLE_FILE}"
done

exit 0
